attempting to do auto-push of gitref into a file

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -13,88 +13,116 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-      - name: Setup Java
-        uses: actions/setup-java@v2
-        with:
-          distribution: "adopt"
-          java-version: "17"
-      - name: RestoreCaches
-        uses: actions/cache@v4
-        env:
-          cache-name: ihub
-        with:
-          path: |
-            .bsp
-            ~/.ivy2
-            ~/.sbt
-            ~/.gradle
-            target
-            project/target
-            project/project/target
-          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('build.sbt') }}
-      - name: Clean
-        run: |
-          rm target/*.jar || true
-          rm -rf target/test-reports || true
-      - name: Set sbt environment variables
-        run: "echo SBT_MEM=2048 >> $GITHUB_ENV; echo SBT_CPUS=2 >> $GITHUB_ENV; echo SBT_TEST_MEM=4096 >> $GITHUB_ENV; echo SBT_TEST_CPUS=2 >> $GITHUB_ENV"
-      - name: Build, check formatting, generate docs, run tests
-        run: "./sbt.sh clean compile test:compile package test"
-        continue-on-error: false
-      - name: Results
-        uses: mikepenz/action-junit-report@v2
-        if: always()
-        with:
-          fail_on_failure: true
-          require_tests: false
-          report_paths: "target/test-reports/TEST-*.xml"
-      - name: Archive the test reports
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-reports
-          path: target/test-reports
-      - name: Set up Docker Buildx
-        id: buildx
-        uses: docker/setup-buildx-action@master
-      - name: PublishImage
-        run: |
-          cd .kube
-          cp ../target/scala-2.12/*.war ./root.war
-      - name: Docker cache layers
-        uses: actions/cache@v4
-        with:
-          path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-single-buildx
+      #      - name: Setup Java
+      #        uses: actions/setup-java@v2
+      #        with:
+      #          distribution: "adopt"
+      #          java-version: "17"
+      #      - name: RestoreCaches
+      #        uses: actions/cache@v4
+      #        env:
+      #          cache-name: ihub
+      #        with:
+      #          path: |
+      #            .bsp
+      #            ~/.ivy2
+      #            ~/.sbt
+      #            ~/.gradle
+      #            target
+      #            project/target
+      #            project/project/target
+      #          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('build.sbt') }}
+      #      - name: Clean
+      #        run: |
+      #          rm target/*.jar || true
+      #          rm -rf target/test-reports || true
+      #      - name: Set sbt environment variables
+      #        run: "echo SBT_MEM=2048 >> $GITHUB_ENV; echo SBT_CPUS=2 >> $GITHUB_ENV; echo SBT_TEST_MEM=4096 >> $GITHUB_ENV; echo SBT_TEST_CPUS=2 >> $GITHUB_ENV"
+      #      - name: Build, check formatting, generate docs, run tests
+      #        run: "./sbt.sh clean compile test:compile package test"
+      #        continue-on-error: false
+      #      - name: Results
+      #        uses: mikepenz/action-junit-report@v2
+      #        if: always()
+      #        with:
+      #          fail_on_failure: true
+      #          require_tests: false
+      #          report_paths: "target/test-reports/TEST-*.xml"
+      #      - name: Archive the test reports
+      #        uses: actions/upload-artifact@v4
+      #        with:
+      #          name: test-reports
+      #          path: target/test-reports
+      #      - name: Set up Docker Buildx
+      #        id: buildx
+      #        uses: docker/setup-buildx-action@master
+      #      - name: PublishImage
+      #        run: |
+      #          cd .kube
+      #          cp ../target/scala-2.12/*.war ./root.war
+      #      - name: Docker cache layers
+      #        uses: actions/cache@v4
+      #        with:
+      #          path: /tmp/.buildx-cache
+      #          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
+      #          restore-keys: |
+      #            ${{ runner.os }}-single-buildx
       - name: Get tag
         id: get-tag
         run: |
           echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
           echo ::set-output name=long_ref::${GITHUB_SHA}
-      - id: auth
-        name: Authenticate with Google Cloud
-        uses: google-github-actions/auth@v2
+    #      - id: auth
+    #        name: Authenticate with Google Cloud
+    #        uses: google-github-actions/auth@v2
+    #        with:
+    #          token_format: access_token
+    #          workload_identity_provider: ${{ env.GCP_PROVIDER_ID }}
+    #          service_account: github-ucroo-integrationhub@flowpoc-386401.iam.gserviceaccount.com
+    #          access_token_lifetime: 600s
+    #      - name: Login to Artifact Registry
+    #        uses: docker/login-action@v1
+    #        with:
+    #          registry: us-central1-docker.pkg.dev
+    #          username: oauth2accesstoken
+    #          password: ${{ steps.auth.outputs.access_token }}
+    #      - id: docker-push-tagged
+    #        name: Tag Docker image and push to Google Artifact Registry
+    #        uses: docker/build-push-action@v2
+    #        with:
+    #          context: .kube/.
+    #          push: true
+    #          file: .kube/Dockerfile
+    #          labels: |
+    #            ihub
+    #          tags: |
+    #            us-central1-docker.pkg.dev/flowpoc-386401/quacker-releases/quacker:${{ steps.get-tag.outputs.long_ref }}
+    #            us-central1-docker.pkg.dev/flowpoc-386401/quacker-releases/quacker:latest
+    outputs:
+      git-ref: steps.get-tag.outputs.long_ref
+  updateRcServers:
+    runs-on: ubuntu-latest
+    needs: [build]
+    # TODO - uncomment this and delete line 138
+    #if: ${{ success() && contains(github.ref,'heads/release') }}
+    env:
+      TARGET_REF: needs.build.outputs.git-ref
+    if: ${{ success() }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name:
+        run: |
+          mkdir -p quackerTemp
+          echo "${{ env.TARGET_REF }}" > quackerTemp/RC_GIT_COMMIT
+      - name: Push
+        uses: dmnemec/copy_file_to_another_repo_action@main
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.FLOW_SERVER_PROVISIONING_API_TOKEN }}
         with:
-          token_format: access_token
-          workload_identity_provider: ${{ env.GCP_PROVIDER_ID }}
-          service_account: github-ucroo-integrationhub@flowpoc-386401.iam.gserviceaccount.com
-          access_token_lifetime: 600s
-      - name: Login to Artifact Registry
-        uses: docker/login-action@v1
-        with:
-          registry: us-central1-docker.pkg.dev
-          username: oauth2accesstoken
-          password: ${{ steps.auth.outputs.access_token }}
-      - id: docker-push-tagged
-        name: Tag Docker image and push to Google Artifact Registry
-        uses: docker/build-push-action@v2
-        with:
-          context: .kube/.
-          push: true
-          file: .kube/Dockerfile
-          labels: |
-            ihub
-          tags: |
-            us-central1-docker.pkg.dev/flowpoc-386401/quacker-releases/quacker:${{ steps.get-tag.outputs.long_ref }}
-            us-central1-docker.pkg.dev/flowpoc-386401/quacker-releases/quacker:latest
+          source_file: "quackerTemp/RC_GIT_COMMIT"
+          destination_repo: "ucroo/flow-server-provisioning"
+          destination_folder: "quackers"
+          user_email: "ci@quacker.pathify.com"
+          user_name: "Continuous Integration Quacker"
+          commit_message: "updated RC to ${{ env.TARGET_REF }}"
